import { $, esc, toNum, tm, mins, downloadText } from './util.js';
import { loadSampleData, parseRakken, parseBojen } from './data.js';
import { saveState, loadState, clearState } from './storage.js';
import { Planner } from './planner.js';
import { initMap, renderBuoys, renderRoute, renderTrack, updateGpsMarker, centerGps } from './map.js';
import { GpsManager } from './gps.js';
import { importExcel } from './importer.js';
const planner=new Planner(); let rawRakken=[], rawBojen=[];
const gps=new GpsManager((pos,err)=>{ $('gpsStatus').textContent=err?'GPS Fehler: '+err.message:(pos?'GPS aktiv':'GPS nicht aktiv'); if(pos) updateGpsMarker(pos); renderAll(); });
function persist(){ saveState({rawRakken,rawBojen,...planner.toJSON(),night:document.body.classList.contains('night')}); $('saveStatus').value='Gespeichert '+new Date().toLocaleTimeString('de-DE'); }
function rebuild(){ planner.setData(parseRakken(rawRakken), parseBojen(rawBojen)); const starts=planner.buoys.filter(b=>b.type==='Startboei').map(b=>b.name).sort(); $('startBuoy').innerHTML=starts.map(s=>`<option>${esc(s)}</option>`).join(''); if(!planner.startBuoy || !starts.includes(planner.startBuoy)) planner.startBuoy=starts[0]||''; $('startBuoy').value=planner.startBuoy; renderAll(); }
function remainingTime(){ const st=mins(planner.startTime), now=new Date(), nm=now.getHours()*60+now.getMinutes(); let rem=st+1440-nm; if(rem<0) rem=0; return Math.floor(rem/60)+'h '+String(rem%60).padStart(2,'0')+'m'; }
function preview(){ const from=planner.current(), to=$('nextBuoy').value, sp=toNum($('speedInput').value), r=planner.routeMap?.get(`${from}|${to}`); if(r&&sp>0){ const eta=tm((planner.state().lastEta==='--:--'?mins(planner.startTime):mins(planner.state().lastEta))+(r.distance/sp)*60); $('preview').textContent=`${r.distance.toFixed(1)} nm | ETA ${eta} | Peilung ${planner.bearing(from,to)||'-'}`; $('addLeg').disabled=false; } else { $('preview').textContent=to?'Bitte Geschwindigkeit größer 0 eingeben.':'Bitte nächste Boje auswählen.'; $('addLeg').disabled=true; } }
function renderAll(){ const st=planner.state(); $('startTime').value=planner.startTime; $('endTime').value=tm(mins(planner.startTime)+1440); $('fromBuoy').value=planner.current(); $('totalNm').textContent=st.total.toFixed(2)+' nm'; $('remainingTime').textContent=remainingTime(); const sog=gps.speedKn(), cog=gps.cogDeg(); $('sogCogEta').textContent=`${sog?Number(sog).toFixed(1):'-'} kn • ${cog?Math.round(cog):'-'}° • ${st.lastEta}`; const allowed=planner.allowed(planner.current()); $('nextCards').innerHTML=allowed.map(to=>{ const r=planner.routeMap.get(`${planner.current()}|${to}`); return `<button class="buoy-card${$('nextBuoy').value===to?' active':''}" data-to="${esc(to)}"><span>${esc(to)}<small>${r?r.distance.toFixed(1)+' nm • '+(planner.bearing(planner.current(),to)||'-'):''}</small></span><span>›</span></button>` }).join('') || '<p class="notice">Keine erlaubten nächsten Bojen verfügbar.</p>';
  document.querySelectorAll('.buoy-card').forEach(b=>b.onclick=()=>{ $('nextBuoy').value=b.dataset.to; preview(); renderAll(); });
  $('recentLegs').innerHTML=st.rows.slice(-8).reverse().map(r=>`<div class="leg-item">${r.row+1}. ${esc(r.from)} → ${esc(r.to)}<small>${r.route?r.route.distance.toFixed(1):''} nm • ${r.bearing||'-'} • ETA ${r.eta||'--:--'} • ${r.status}</small></div>`).join('') || '<p class="notice">Noch keine Schläge geplant.</p>';
  $('planTable').querySelector('tbody').innerHTML=st.rows.map(r=>`<tr class="${r.status==='OK'?'ok':r.status?'warn':''}"><td>${r.row+1}</td><td>${esc(r.from)}</td><td>${esc(r.to)}</td><td>${r.route?r.route.distance.toFixed(1):''}</td><td>${r.bearing}</td><td>${r.speed}</td><td>${r.eta}</td><td>${r.status}</td></tr>`).join('');
  $('overviewTable').querySelector('tbody').innerHTML=planner.routes.map(r=>{ const g=st.counts[r.id]||0, status=g>r.max?'Max überschritten':g?'OK':'offen'; return `<tr><td>${esc(r.start)} → ${esc(r.end)}</td><td>${r.distance.toFixed(1)}</td><td>${r.max}</td><td>${g}</td><td>${status}</td></tr>`}).join('');
  if(window.L){ renderRoute(planner, $('routeOverlayToggle')?.checked); renderTrack(gps.log, $('gpsTrackToggle')?.checked); }
  preview(); }
function switchView(id){ document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id)); document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); if(id==='mapview'){ initMap(); renderBuoys(planner.buoys); renderRoute(planner, $('routeOverlayToggle').checked); renderTrack(gps.log, $('gpsTrackToggle').checked); } }
async function boot(){ if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(console.warn); const saved=loadState(); if(saved?.rawRakken){ rawRakken=saved.rawRakken; rawBojen=saved.rawBojen; planner.fromJSON(saved); document.body.classList.toggle('night', !!saved.night); } else { ({rawRakken,rawBojen}=await loadSampleData()); } rebuild();
  document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view)); $('themeToggle').onclick=()=>{document.body.classList.toggle('night');persist()}; $('startTime').oninput=e=>{planner.startTime=e.target.value;renderAll();persist()}; $('startBuoy').onchange=e=>{planner.startBuoy=e.target.value;planner.plan=[];$('nextBuoy').value='';renderAll();persist()}; $('speedInput').oninput=preview; $('addLeg').onclick=()=>{ if(planner.addLeg($('nextBuoy').value,$('speedInput').value)){ $('nextBuoy').value=''; $('speedInput').value=''; renderAll(); persist(); } }; $('undoLeg').onclick=()=>{planner.undo(); renderAll(); persist()}; $('useGpsSpeed').onclick=()=>{ const s=gps.speedKn(); if(s){$('speedInput').value=Number(s).toFixed(1); preview();} };
  $('manualSave').onclick=persist; $('exportJson').onclick=()=>downloadText('regatta-stand.json', JSON.stringify({rawRakken,rawBojen,...planner.toJSON()},null,2), 'application/json;charset=utf-8'); $('resetApp').onclick=()=>{ if(confirm('Lokale Daten löschen und Beispieldaten laden?')){ clearState(); location.reload(); } }; $('loadJsonBtn').onclick=()=>$('loadJson').click(); $('loadJson').onchange=async e=>{ const f=e.target.files[0]; if(!f)return; const s=JSON.parse(await f.text()); rawRakken=s.rawRakken; rawBojen=s.rawBojen; planner.fromJSON(s); rebuild(); persist(); };
  $('importExcel').onclick=async()=>{ try{ ({rawRakken,rawBojen}=await importExcel($('rakkenFile').files[0], $('bojenFile').files[0])); planner.plan=[]; rebuild(); persist(); $('importMsg').textContent='Import erfolgreich.'; } catch(e){ $('importMsg').textContent=e.message; } };
  $('startGps').onclick=()=>{ try{ gps.start(); $('gpsStatus').textContent='GPS wird angefragt...'; } catch(e){ $('gpsStatus').textContent=e.message; } }; $('stopGps').onclick=()=>{gps.stop(); $('gpsStatus').textContent='GPS gestoppt'; renderAll();}; $('centerGps').onclick=()=>centerGps(gps.last); $('exportGpsCsv').onclick=()=>gps.exportCsv(); $('exportGpsGpx').onclick=()=>gps.exportGpx(); $('routeOverlayToggle').onchange=renderAll; $('gpsTrackToggle').onchange=renderAll;
  $('simEnabled').onchange=e=>{gps.sim.enabled=e.target.value==='on'; $('simStatus').textContent=gps.sim.enabled?'Simulation aktiv':'Simulation aus'; if(gps.sim.enabled) $('speedInput').value=Number(gps.sim.sog).toFixed(1); renderAll();}; $('simSog').oninput=e=>{gps.sim.sog=Number(e.target.value||0); if(gps.sim.enabled) $('speedInput').value=gps.sim.sog.toFixed(1); renderAll();}; $('simCog').oninput=e=>{gps.sim.cog=Number(e.target.value||0); renderAll();};
  let sx=0; document.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true}); document.addEventListener('touchend',e=>{ const dx=e.changedTouches[0].screenX-sx; if(Math.abs(dx)<80) return; const ids=[...document.querySelectorAll('.bottom-nav button')].map(b=>b.dataset.view); const cur=ids.findIndex(id=>document.getElementById(id).classList.contains('active')); switchView(ids[(cur+(dx<0?1:-1)+ids.length)%ids.length]); },{passive:true});
}
boot();
