import { esc } from './util.js';
let map, buoyLayer, routeLayer, trackLayer, gpsMarker;
const color=t=>t==='Startboei'?'green':t==='Finishboei'?'gold':'#3388ff';
export function initMap(){ if(!window.L) return null; if(map){ setTimeout(()=>map.invalidateSize(),80); return map; } map=L.map('map').setView([52.8,5.2],8); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map); L.tileLayer('https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenSeaMap contributors'}).addTo(map); buoyLayer=L.layerGroup().addTo(map); routeLayer=L.layerGroup().addTo(map); trackLayer=L.layerGroup().addTo(map); return map; }
export function renderBuoys(buoys){ if(!initMap()||!buoyLayer) return; buoyLayer.clearLayers(); const bounds=[]; buoys.filter(b=>Number.isFinite(b.lat)&&Number.isFinite(b.lon)).forEach(b=>{ L.circleMarker([b.lat,b.lon],{radius:b.type==='Startboei'?7:5,color:color(b.type),weight:2,fillColor:color(b.type),fillOpacity:.25}).bindPopup(`<b>${esc(b.name)}</b><br>${esc(b.type)}${b.description?'<br>'+esc(b.description):''}`).addTo(buoyLayer); bounds.push([b.lat,b.lon]); }); if(bounds.length) map.fitBounds(bounds,{padding:[20,20]}); }
export function renderRoute(planner, enabled=true){ if(!initMap()||!routeLayer) return; routeLayer.clearLayers(); if(!enabled) return; const seen={}; planner.state().rows.forEach(s=>{ const a=planner.buoys.find(b=>b.name===s.from), b=planner.buoys.find(x=>x.name===s.to); if(!a||!b||!Number.isFinite(a.lat)||!Number.isFinite(b.lat)) return; seen[s.id]=(seen[s.id]||0)+1; const opts={color:'#d97706',weight:4,opacity:.9}; if(seen[s.id]===1) opts.dashArray='8 8'; L.polyline([[a.lat,a.lon],[b.lat,b.lon]],opts).bindPopup(`<b>${esc(s.from)} → ${esc(s.to)}</b><br>${s.route?s.route.distance.toFixed(1)+' nm':''}`).addTo(routeLayer); }); }
export function renderTrack(log, enabled=true){ if(!initMap()||!trackLayer) return; trackLayer.clearLayers(); if(!enabled || !log || log.length<2) return; const pts=log.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)).map(p=>[p.lat,p.lon]); if(pts.length>1) L.polyline(pts,{color:'#2563eb',weight:4,opacity:.85}).bindPopup(`GPS-Track<br>${pts.length} Logpunkte`).addTo(trackLayer); }
export function updateGpsMarker(pos){ if(!initMap()||!pos) return; const lat=pos.coords.latitude, lon=pos.coords.longitude; if(!gpsMarker) gpsMarker=L.circleMarker([lat,lon],{radius:8,color:'red',fillColor:'red',fillOpacity:.9}).bindPopup('GPS').addTo(map); gpsMarker.setLatLng([lat,lon]); }
export function centerGps(pos){ if(map&&pos) map.setView([pos.coords.latitude,pos.coords.longitude],14); }
